# Generated by Django 5.2.6 on 2025-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('companion', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=100)),
                ('lodging', models.CharField(max_length=100)),
                ('attractions', models.TextField(max_length=250)),
                ('notes', models.TextField(max_length=250)),
            ],
        ),
    ]
