# Generated by Django 5.2.6 on 2025-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_transportation_stretch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='Transportation_stretch',
        ),
    ]
