# Generated by Django 5.2.6 on 2025-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_attraction_delete_transportation_stretch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attractions_stretch',
            field=models.ManyToManyField(to='main_app.attraction'),
        ),
    ]
