# Generated by Django 5.2.6 on 2025-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_trip_attractions_stretch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attractions_stretch',
        ),
        migrations.AddField(
            model_name='trip',
            name='old_attractions',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='trip',
            name='attractions',
        ),
        migrations.AddField(
            model_name='trip',
            name='attractions',
            field=models.ManyToManyField(to='main_app.attraction'),
        ),
    ]
