# Generated by Django 5.2.6 on 2025-09-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_trip_attractions_stretch_trip_old_attractions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_stretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('departure_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('ticket_number', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=250)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip')),
            ],
        ),
    ]
