# Generated by Django 5.2.6 on 2025-09-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_transportation_stretch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transportation_stretch',
            new_name='Transportation',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='transportation',
            new_name='old_transportation',
        ),
    ]
